### ISSUE TITLE
Windows Defender flags FlashGBX as a trojan horse

### ISSUE THREAD

**Issue by Siphonay** [lesserkuma/FlashGBX#2]
Hey there, I’ve had FlashGBX suddenly close itself, and the executable getting automatically deleted and I couldn’t understand why. When I redownloaded it, it wouldn’t launch, I was getting a warning that it’s a malicious program. I just looked into Windows Defender’s logs and found this

![image](https://user-images.githubusercontent.com/6833300/101098358-1446a100-35c3-11eb-9ff3-9aa10d91660a.png)

I hope that’s a false negative and that you can fix it if you manage to reproduce it, because otherwise FlashGBX has been the best frontend for my GBxCart RW.

Have a nice day!

**Comment by lesserkuma** [comment]
Hey, thanks for the report!
It seems like this is a widespread *false positive* issue with [PyInstaller](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed). I will try and compile the PyInstaller bootloader from source for the next release. I’m also planning to submit a report to Microsoft.

**Comment by lesserkuma** [comment]
According to VirusTotal and Jotti’s Malware Scan, Windows Defender should no longer have a problem with the new version which was released today. I hope this fixes the issue for you as well!

**Comment by Siphonay** [comment]
Sorry for the late reply but I can confirm I’m not having this issue anymore. Thanks for taking care of it!

**Comment by Sheeg** [comment]
This issue appears to have returned for the windows x64 installer version of FlashGBX v5.1, Windows 11 flags it the zip file as a trojan and deletes it. The non-installer zip is fine.

<img width="947" height="430" alt="Image" src="https://github.com/user-attachments/assets/765522d0-4ae4-4783-9d5d-404e3f280e31" />

**Comment by Lesserkuma** [comment]
All that was changed in the build workflow was the upgrade to InnoSetup 7:
https://github.com/Lesserkuma/FlashGBX/commit/0272d8ef039b2e131a7278c1a3b6dd4ade5a7ecd#diff-a3ae20db8d6f829cce559bf09c6fa26bf26822b30ab4994444b49a0b9909470e

I guess I'll revert to the old version 🙁
