### ISSUE TITLE
Compatibility with 2006_TSOP_64BALL_QFP48

### ISSUE THREAD

**Issue by Sithdown** [lesserkuma/FlashGBX#20]
I've received a reproduction Game Boy cartridge with this version: 2006_TSOP_64BALL_QFP48

I'm not sure FlashGBX is able to flash this cartridge. Any tips?

![image](https://user-images.githubusercontent.com/430612/134514180-01c0dad9-0754-48f5-97c4-0c0a3cc6bc67.png)

**Comment by Sithdown** [comment]
Hi!

It's a bootleg GBC Pokemon Yellow (Spanish Version) from Aliexpress. It's from this seller:
[aliexpress.com/item/1005001537927786.html?spm=a2g0s.9042311.0.0.656f63c0hdcHDQ](aliexpress.com/item/1005001537927786.html?spm=a2g0s.9042311.0.0.656f63c0hdcHDQ)

I was curious because I haven't seen this PCB on previous cartridges. It seems every seller has its own version.

I'm waiting for my FlashGBX to arrive (1-2 weeks), so I'll be able to get more info then. I hope we can learn something about this version by then!

Thank you for your time :)

**Comment by Sithdown** [comment]
Hello again!

I've finally checked the cartridge with FlashGBX and GBxCart RW 1.4, firmware version R31+L2.

![image](https://user-images.githubusercontent.com/430612/135929760-43a6734c-fc57-4a75-a80a-f15e6ff4d368.png)

When doing a ROM backup, the checksum is not correct.

If I Auto-detect the flash cartridge, it looks like it's compatible:

![image](https://user-images.githubusercontent.com/430612/135929925-b388f854-f8b5-4a44-8c08-e0ba634aa925.png)

So it seems it's a "SD007_BV5_V3 with AM29LV160MB".


Is it safe to write a ROM on this flashcart? I don't want to brick it that soon 😅

**Comment by lesserkuma** [comment]
Oh cool, glad it works! It seems to work exactly the same as the four others that are currently listed by FlashGBX, so I will add yours to that list soon, probably going to call it “2006_TSOP_64BALL_QFP48 with AL016J55FFAR2”. Thanks again!

**Comment by Sithdown** [comment]
Resolved by d2abd30
