### ISSUE TITLE
As for the problem of diyGBC burning card chip

### ISSUE THREAD

**Issue by dyf2007** [lesserkuma/FlashGBX#21]
As for the problem of diyGBC burning card chip, I use AM29F016B-75SI and use general to burn normal games. I hope that god can add this chip. The following picture is the chip data. Thank you for updating this software.
![IMG_20211208_163716](https://user-images.githubusercontent.com/84038001/145184288-dc1cb7e8-7b99-4ff3-9cc6-edcfc09a0225.jpg)
![IMG_20211208_172735](https://user-images.githubusercontent.com/84038001/145184306-701fa753-6336-4ced-bf95-76d6f6f0d2a0.jpg)
![IMG_20211208_164829](https://user-images.githubusercontent.com/84038001/145184313-1ea13954-a8f1-4de0-a1e9-f7148dd816da.jpg)
![IMG_20211208_170812](https://user-images.githubusercontent.com/84038001/145184319-a7c01e9d-dbb2-447a-bb1a-47f9d7ecfb45.jpg)
![IMG_20211208_164725](https://user-images.githubusercontent.com/84038001/145184323-90b5c962-f39b-4fdf-8e7d-e254c86fef8d.jpg)

**Comment by dyf2007** [comment]
![Uploading 2021-12-08_17.22.27.jpg…]()

**Comment by lesserkuma** [comment]
Very nice! Can you write the ROM successfully with your newly added setting?

**Comment by dyf2007** [comment]
> Very nice! Can you write the ROM successfully with your newly added setting?

Can, the game can be written correctly and effect, the game can play normally, half a year ago this burning card is done, has been modified with this burning game, tried a lot of games。

**Comment by lesserkuma** [comment]
Thank you for your contribution, I will add it to the next release based on your pictures!
