### ISSUE TITLE
Compatibility with Flash2Advance 128M Flash Card

### ISSUE THREAD

**Issue by twitnic** [lesserkuma/FlashGBX#22]
Is it possible to add this card to FlashGBX?

<img width="1271" alt="Bildschirmfoto 2021-12-23 um 01 29 31" src="https://user-images.githubusercontent.com/1270942/147169922-27a7a1de-c97a-4bba-9f7b-c49f6647a017.png">

![IMG_7008](https://user-images.githubusercontent.com/1270942/147169964-007d58db-07b5-4abd-ac9b-1f1662ed793a.jpeg)

```
The following cartridge configuration was detected:

Game Title: GB_Lo_er

Flash ID Check:
[   ROM   ] 2E 00 89 00 24 FF 17 00 
[   555/AA] 89 00 00 EA 17 00 AE 51 
[   555/A9] 89 00 00 EA 17 00 AE 51 
[  5555/AA] 89 00 00 EA 17 00 AE 51 
[  5555/A9] 89 00 00 EA 17 00 AE 51 
[  4555/AA] 89 00 00 EA 17 00 AE 51 
[  4555/A9] 89 00 00 EA 17 00 AE 51 
[  7555/AA] 89 00 00 EA 17 00 AE 51 
[  7555/A9] 89 00 00 EA 17 00 AE 51 
[     0/90] 89 00 89 00 17 00 17 00 

Common Flash Interface Data: No data provided

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board. For ROM writing, you can give the option called “Generic Flash Cartridge (0/90)” a try.

FlashGBX v3.2 | GBxCart RW v1.4 – Firmware R33+L4 (/dev/cu.usbserial-1430)
```

**Comment by lesserkuma** [comment]
Hi! Yeah, I think I can add this cartridge. As there are different revisions of the Flash2Advance cartridges, would it be possible for you to open the cartridge and take a picture of the circuit board with readable chip markings?

**Comment by twitnic** [comment]
![image](https://user-images.githubusercontent.com/1270942/147391802-54a516af-f86e-4ea2-8c19-e4c4f1634104.jpeg)

![image](https://user-images.githubusercontent.com/1270942/147391810-24f0e664-a939-42be-9e57-8b6ee52c0db2.jpeg)

I hope that helps.

**Comment by lesserkuma** [comment]
Yes that helps and it seems to be very similar to the 256M cartridge that I own, so this might work!

1. Click [Config] → Show configuration directory
2. Download and copy [fc_AGB_Flash2Advance_128M.txt](https://github.com/lesserkuma/FlashGBX/files/7776955/fc_AGB_Flash2Advance_128M.txt) into the folder that opened
3. Restart FlashGBX

With this, the software should be able to auto-detect your cartridge. Then please test if you can successfully write a 16 MB ROM file!

**Comment by twitnic** [comment]
It works. Sorry I was busy (Christmas Holidays .. )

I put the txt file into the config folder and tried to write a rom to the cartridge. it was successfully :)

Thanks !

<img width="532" alt="Bildschirmfoto 2021-12-31 um 15 49 59" src="https://user-images.githubusercontent.com/1270942/147829215-61ebb4de-7eda-4fb6-a64c-a64424075c3c.png">
<img width="852" alt="Bildschirmfoto 2021-12-31 um 15 51 54" src="https://user-images.githubusercontent.com/1270942/147829218-ec8b252e-16cb-4775-ab01-c12e4c8a6e13.png">

**Comment by lesserkuma** [comment]
I’m glad to hear that! It will be added to the next release version as well :) Thank you!
