### ISSUE TITLE
Compatibility with other  cartridge 4050_4400_4000_4350_36L0R_V5 

### ISSUE THREAD

**Issue by nonochus** [lesserkuma/FlashGBX#30]
Hello, first of all, great job!very thanks!

I have a few carts labeled as : 4050_4400_4000_4350_36L0R_V5  but can´t flash in this carts, all goes well but when i put in the console, hangs after logo.

Seens to be 4050_4400_4000_4350_36L0R_V5 with  a 4050V0YBQ1 chip, this is what i get with detect flash, then  details:

Game Title: NINJA COP 
ROM Size: 32 MB
Save Type: 512K SRAM (64 KB)

Flash ID Check:
[   ROM   ] 2E 00 00 EA 24 FF AE 51 
[   555/A9] 8A 00 1C 88 02 00 02 00 
[  5555/A9] 8A 00 1C 88 02 00 02 00 
[   AAA/A9] 8A 00 1C 88 02 00 02 00 
[  AAAA/A9] 8A 00 1C 88 02 00 02 00 
[  4555/A9] 8A 00 1C 88 02 00 02 00 
[  7555/A9] 8A 00 1C 88 02 00 02 00 
[  4AAA/A9] 8A 00 1C 88 02 00 02 00 
[  7AAA/A9] 8A 00 1C 88 02 00 02 00 
[     0/90] 8A 00 1C 88 02 00 02 00 

Common Flash Interface Data:
Swapped pins: (0, 1)
Device size: 0x2000000 (32.00 MB)
Voltage: 1.7–2.0 V
Single write: True
Buffered write: True (64 Bytes)
Sector erase: 1024–4096 ms
Region 1: 0x0000000–0x001FFFF @ 0x8000 Bytes × 4
Region 2: 0x0020000–0x1FFFFFF @ 0x20000 Bytes × 255

Compatible Cartridge Types:
- 36L0R8-39VF512 with M36L0R8060B*
- 36L0R8-39VF512 with M36L0R8060T
- 4050_4400_4000_4350_36L0R_V5 with 4050L0YTQ2
- 4050_4400_4000_4350_36L0R_V5 with M36L0R8060T
- 4350Q2 with 4050V0YBQ1
- 4350Q2 with 4350LLYBQ2

FlashGBX v3.5 | GBxCart RW v1.3 – Firmware L1 (COM3)

I try all compatible cartirdge types, all hangs after bios.

Can be added this cart?

Very thanks!

**Comment by lesserkuma** [comment]
Hi! If it says “The ROM was written and verified successfully!”, that means the problem lies with either the ROM file or the cartridge. It’s possible that the ROM uses a different save type than what your cartridge supports. You can use [GBATA](https://www.romhacking.net/utilities/601/) to change the save type from EEPROM 4K/64K or FLASH 512K to SRAM. But do note that if your cartridge uses SRAM but has no battery installed, the game will not be able to save progress. See this site for more info: https://flashcartdb.com/index.php/Clone_and_Repo_Cart_Problems. You can also join the [insideGadgets Discord](https://www.gbxcart.com/discord) to get help from the community!

**Comment by nonochus** [comment]
Hi, yes, it says “The ROM was written and verified successfully!” but still not working, i try to flash a rom without saves (a rom file that uses password instead save) and roms with sram patch that flash and work well in others carts, and ever hangs in bios, keep in white screen after show bios logo.

Thr rom file can´t be the problem, same rom file flash well in other carts, i try a lot of rom confirmes working, and the cartridge itself, i have 5 of this carts and the 5 hangs.

Also this carts have battery, the cart is a compilation of 150 games of nes named "nes classic"

**Comment by nonochus** [comment]
I go to try to flash the carts with the full erase option to see if works....

**Comment by lesserkuma** [comment]
Oh, the 150 NES Classics cartridge I have also only works with homebrew software, NOT with backups of retail games. What you can try is to use the [Supercard software](http://eng.supercard.sc/old/download/setupsdV271en.zip) to apply the SRAM patch. This software will also slow down cart access timing which seems to be needed for this cartridge.

**Comment by nonochus** [comment]
Yes!with supercard software works!i can flash retail games!very thanks!!!!
