### ISSUE TITLE
Unknown flash cartridge

### ISSUE THREAD

**Issue by zvxr** [lesserkuma/FlashGBX#32]
The following cartridge configuration was detected:

Game Title: POWDER117
Save Type: Unlicensed 512K SRAM (64 KB)

Flash ID Check:
[   ROM   ] 2E 00 00 EA 24 FF AE 51 
[  5555/A9] 02 00 02 EA 7D FF 7D 51 

Common Flash Interface Data: No data provided

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board.

FlashGBX v3.7 | GBxCart RW v1.4a – Firmware R32+L3 (/dev/cu.usbserial-1420)

https://drive.google.com/file/d/1WtGnQB-vR9dRsWfg0JtiG_mvMZxu25JU/view?usp=sharing
https://drive.google.com/file/d/1P2ttIjass0quki6rXvmaPN28YAwQgvh4/view?usp=sharing

**Comment by lesserkuma** [comment]
Hi! If it says MSP55LV100G on that flash chip, please try the following:
1. Update your firmware to version R34+L5 via [Tools] → Firmware Updater
2. Click [Config] → Show configuration directory
3. Download [this file](https://raw.githubusercontent.com/lesserkuma/FlashGBX/4a91df2f71d994be1de7f9e12e5b73a4e469c470/FlashGBX/config/fc_AGB_MSP55LV100G.txt) and move it into the config folder that opened
4. Restart FlashGBX

Let me know if that works!
