### ISSUE TITLE
Can't detected AGB-E02-20

### ISSUE THREAD

**Issue by aszzq** [lesserkuma/FlashGBX#35]
Pokémon LeafGreen Version(JP)
![e20dc65c1038534381460734ce13b07ecb8088c6](https://user-images.githubusercontent.com/103807993/163663513-a40e529e-a3c3-45e6-ae4d-6d86e525100e.jpg)
![20220416135442](https://user-images.githubusercontent.com/103807993/163663630-ef732df9-2f72-434d-9c4a-8db148a3922c.png)
![ff1f1f30e924b899e8a3e42d33061d950a7bf634](https://user-images.githubusercontent.com/103807993/163663858-773791c0-a5c1-4485-b159-c8ce06d1ed0d.jpg)

**Comment by lesserkuma** [comment]
Hi, can you try again with the latest version of FlashGBX?
You can find it here: https://github.com/lesserkuma/FlashGBX/releases/latest

If it still doesn’t work, try to clean the cartridge contacts very thoroughly. You can also try not to push the cartridge all the way into the cart reader. I tested my Japanese Pocket Monsters Leaf Green cartridge and it works ok on FlashGBX v3.7 using GBxCart RW v1.3 on firmware L1.

![](https://user-images.githubusercontent.com/67554470/163713124-09ea9d1e-8a0f-42d1-87ab-55a984aa4cc5.png)
![](https://user-images.githubusercontent.com/67554470/163713063-6d127dca-8879-480a-9927-fbbf43647971.png)

**Comment by aszzq** [comment]
> Hi, can you try again with the latest version of FlashGBX? You can find it here: https://github.com/lesserkuma/FlashGBX/releases/latest
> 
> If it still doesn’t work, try to clean the cartridge contacts very thoroughly. You can also try not to push the cartridge all the way into the cart reader. I tested my Japanese Pocket Monsters Leaf Green cartridge and it works ok on FlashGBX v3.7 using GBxCart RW v1.3 on firmware L1.
> 
> ![](https://user-images.githubusercontent.com/67554470/163713124-09ea9d1e-8a0f-42d1-87ab-55a984aa4cc5.png) ![](https://user-images.githubusercontent.com/67554470/163713063-6d127dca-8879-480a-9927-fbbf43647971.png)

Hi, I have cleaned the cartridge contacts contacts with alcohol，then used FlashGBX v3.7.
IT still doesn’t work.

![QQ截图20220418095222](https://user-images.githubusercontent.com/103807993/163742621-02fe9d6e-6b3e-4cac-82cf-8f8785a33698.png)

**Comment by lesserkuma** [comment]
Thanks for checking. In that case, I don’t think the problem is related to my software. It seems to be a connectivity problem or a hardware issue with either the cartridge or the GBxCart RW device.

You could change the firmware to version R30 and try again with insideGadgets’ official software: https://shop.insidegadgets.com/wp-content/uploads/2018/05/GBxCart_RW_GUI_Interface_v1.49.zip
If it still doesn’t work, maybe contact insideGadgets customer support.

**Comment by aszzq** [comment]
> Thanks for checking. In that case, I don’t think the problem is related to my software. It seems to be a connectivity problem or a hardware issue with either the cartridge or the GBxCart RW device.
> 
> You could change the firmware to version R30 and try again with insideGadgets’ official software: https://shop.insidegadgets.com/wp-content/uploads/2018/05/GBxCart_RW_GUI_Interface_v1.49.zip If it still doesn’t work, maybe contact insideGadgets customer support.

Not working.
I send it to someone who have the game for testing.

**Comment by aszzq** [comment]
Something wrong with the PCB what I drew. I redraw the PCB，That's OK.
