### ISSUE TITLE
Backlog: Extremely slow under macOS

### ISSUE THREAD

**Issue by ClassicOldSong** [lesserkuma/FlashGBX#4]
When flashing using macOS, it went extremely slow. When flashing using Linux it could go to about 20KB/s, while in macOS it only goes to about 8KB/s.

**Comment by ClassicOldSong** [comment]
Interesting, using raspberry pi as a serial adapter it works much faster:

![image](https://user-images.githubusercontent.com/10512422/102505318-ccdd0c00-40bc-11eb-8208-1b00af268fae.png)

**Comment by ClassicOldSong** [comment]
Commands on rpi:

```shell
modprobe dwc2
modprobe g_serial
stty -F /dev/ttyGS0 raw -echo
stty -F /dev/ttyAMA0 raw -echo 1000000
socat FILE:/dev/ttyGS0 FILE:/dev/ttyAMA0
```

**Comment by lesserkuma** [comment]
I heard about different speeds on different machines, but I’m not exactly sure why that is.
Can you try to compile the [official GBxCart RW software](https://github.com/insidegadgets/GBxCart-RW) and measure its speed on the same machine?

**Comment by ClassicOldSong** [comment]
The official one could not even open the ch340 device.

Interestingly enough, after I modified the program to recognize usbmodem, it works perfectly well with my rpi adapter.

**Comment by lesserkuma** [comment]
> Interestingly enough, after I modified the program to recognize usbmodem, it works perfectly well with my rpi adapter.
Interesting, it does seem like performance partially depends on the driver. I also noticed serial drivers on different operating systems can have different input buffer sizes which may also be affecting performance and functionality; on Windows it seems to be at least 65536 bytes (didn’t test for more), on Ubuntu 4095 bytes and on macOS only 1020 bytes.

**Comment by bbsan2k** [comment]
The CH34X kext that is provided with macos is pretty crappy... there is a (commercial) alternative driver, although the devs are currently struggling to establish support with Apples Driverkit. (https://www.mac-usb-serial.com/)

**Comment by lesserkuma** [comment]
Thanks everyone! I’m closing this for now because I don’t think there is anything I could do if it's a driver-related issue.

**Comment by lesserkuma** [comment]
Thanks everyone! I’m closing this for now because I don’t think there is anything I could do if it’s a driver-related issue.
