### ISSUE TITLE
weird behaviour when path to FlashGBX.exe contains square brackets (like "D:\[a]\FlashGBX\")

### ISSUE THREAD

**Issue by kscheel** [lesserkuma/FlashGBX#51]
This occurred to me with "FlashGBX_3.18_Windows_Portable".

Weird behaviour:

- crash every 2nd start, presumably because settings.ini can't be read? The config folder will contain a file like "settings.ini_20220828210320.bak" afterwards.
- FlashCarts won't be detected correctly and can't be flashed. I was already thinking my new FlashCart was broken 😭 
- (Dumping ROMs etc was working fine)

I can post more details about what happened when I tried to detect my flashcart or write a ROM to it. Just let me know if that would be helpful.

After I copied FlashGBX into a different folder everything was working just fine, lmao. This was my last resort after about an hour of fiddling ^^ Anyway, thanks for creating and maintaining this great tool! :)

**Comment by lesserkuma** [comment]
Thanks, this will be fixed in the next release!
