### ISSUE TITLE
Retry on failed sector write

### ISSUE THREAD

**Issue by corwinkuiper** [lesserkuma/FlashGBX#55]
When attempting to write a rom to a cartridge, it fails after some random time. I've seen it write 2MB without error before failing, but at some point with large roms it fails.
![image](https://user-images.githubusercontent.com/8143879/202044890-92c5bb2b-616a-4178-b9d1-28724d068396.png)

If rather than restarting the whole process, if it could retry to write the failed writes then I think it should increase the likelihood of writing the whole rom.

**Comment by lesserkuma** [comment]
I released the new version today. I hope it works for you!

**Comment by corwinkuiper** [comment]
Works flawlessly, thanks very much!
![image](https://user-images.githubusercontent.com/8143879/205056099-8f7e5864-89e2-40de-80f3-2507af2c553d.png)
