### ISSUE TITLE
Support for manual MBC switching on AUDIO carts

### ISSUE THREAD

**Issue by ALXCO-Hardware** [lesserkuma/FlashGBX#57]
Following the discussion on the official Discord, I will post this suggestion here as an issue.

When using a flashcart with multiple Flash chips, it is convenient to be able to manually change the memory bank in use, to address specific ICs during an operation. 
When the IC's WE pin is tied to the cartridge's WR pin, this can be done by manually adding MBC writes to the command sequence, as in:

[ 0x2100, 0x80 ], -- switches to bank 128
[ 0x2100, 0x00 ], -- switches to bank 0

However, in a flashcart that ties WE to the VIN/AUDIO pin instead, the previous commands have no effect - Since the MBC's WR pin is never asserted, it does not recognize the bank switching operation.

Two alternate solutions were proposed for this issue. 

The first one would be to add an option to the "write_pin" key on the config files that would set it to output on both AUDIO and WR at once.

The second one, suggested by AlexiG, would be to add the option to override the choice of write pin on specific commands, with the following syntax:

[ 0x4AAA, 0xAA, AUDIO ],
...
[ 0x2100, 0x80, WR ],

Thank you for your time!

**Comment by lesserkuma** [comment]
Thanks, this feature will be added in the next release for the sector erase and chip erase commands!
