### ISSUE TITLE
Application won't run on macOS Big Sur

### ISSUE THREAD

**Issue by paarongiroux** [lesserkuma/FlashGBX#6]
It seems that qt5 doesn't run on macOS Big Sur. When running the application, python freezes and the GUI is never displayed.

Adding the following lines to run.py fixes the problem entirely: 
```
import os 
os.environ['QT_MAC_WANTS_LAYER'] = '1'
```

Thought I'd document here in case anyone runs into the same problem

**Comment by lesserkuma** [comment]
Thanks for the bug report! I added your fix to the main program, let me know if the problem persists.

**Comment by twadepsvita** [comment]
What I do is I open the run.py with IDLE, press F5, then it works for me.
