### ISSUE TITLE
Can I use this cart?

### ISSUE THREAD

**Issue by ccs21** [lesserkuma/FlashGBX#67]
There are no words other than DRV written on the board.

Running the detect gave me the following results:

Attach photos together.

`The following cartridge configuration was detected:

Game Title: POKEMON_SLV
Save Type: 1M SRAM (128 KB)

Flash ID Check:
[     ROM     ] F3 C3 00 01 00 00 00 00 
[WR   /4AAA/A9] 02 02 4A 4A 00 00 00 00 
[WR   /7AAA/A9] 02 02 4A 4A 00 00 00 00 

Common Flash Interface Data:
Swapped pins: (0, 1)
Device size: 0x0200000 (2.00 MB)
Voltage: 2.7–3.6 V
Single write: True
Buffered write: False
Sector erase: 1024–16384 ms
Region 1: 0x0000000–0x0003FFF @ 0x4000 Bytes × 1
Region 2: 0x0004000–0x0007FFF @ 0x2000 Bytes × 2
Region 3: 0x0008000–0x000FFFF @ 0x8000 Bytes × 1
Region 4: 0x0010000–0x01FFFFF @ 0x10000 Bytes × 31

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board.

FlashGBX v3.21 | GBxCart RW v1.4a – Firmware R39+L8
`

![image](https://user-images.githubusercontent.com/24364147/215032919-7cdc0864-d900-490a-83d5-b90d5b9792ff.png)

![KakaoTalk_20230127_163814920_04](https://user-images.githubusercontent.com/24364147/215033462-80a5bf96-babc-4add-bbce-87d6a62f046f.jpg)

![KakaoTalk_20230127_163814920_03](https://user-images.githubusercontent.com/24364147/215033476-0beab7b4-7cd9-451b-b662-eadd77cb5b3d.jpg)

![KakaoTalk_20230127_163814920_02](https://user-images.githubusercontent.com/24364147/215033506-0ecd87c3-476a-4f13-b321-a64bc158610e.jpg)

![KakaoTalk_20230127_163814920_01](https://user-images.githubusercontent.com/24364147/215033523-e5aa608d-b658-48b8-ac7c-77b5a23e1276.jpg)

![KakaoTalk_20230127_163814920](https://user-images.githubusercontent.com/24364147/215033540-6a397d66-de7a-470a-804b-f2567d061c96.jpg)

**Comment by lesserkuma** [comment]
Thanks! Can you try if this option would work?
`SD007_48BALL_64M with GL032M11BAIR4`
Manually select it from the list, then click Write ROM. The maximum ROM size is 2 MB.

**Comment by ccs21** [comment]
It Works!

Thanks a lot!!!!

**Comment by lesserkuma** [comment]
Nice! I’ll add it to the auto-detect for the next release! ^^
