### ISSUE TITLE
cannot auto-detecte

### ISSUE THREAD

**Issue by ccs21** [lesserkuma/FlashGBX#68]
![KakaoTalk_20230131_214902071](https://user-images.githubusercontent.com/24364147/215764385-8a4870f3-d00d-4135-8a9b-b2c616e82aa0.jpg)

The following cartridge configuration was detected:

Game Title: POKEMON_GLD
Save Type: 1M SRAM (128 KB)

Flash ID Check:
[     ROM     ] F3 C3 00 01 00 00 00 00 
[WR   / 555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /5555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /4555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /7555/A9] 04 C7 00 00 04 C7 00 00 

Common Flash Interface Data: No data provided

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board. For ROM writing, you can give the option called “Generic Flash Cartridge (WR/555/A9)” a try at your own risk.

FlashGBX v3.21 | GBxCart RW v1.4a – Firmware R39+L8

![KakaoTalk_20230131_204714849](https://user-images.githubusercontent.com/24364147/215764429-fa843cba-a2e6-4ee5-9afb-9347739ca637.jpg)

The following cartridge configuration was detected:

Game Title: POKEMON_GLD
Save Type: 256K SRAM (32 KB)

Flash ID Check:
[     ROM     ] F3 C3 00 01 00 00 00 00 
[WR   / 555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /5555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /4555/A9] 04 C7 00 00 04 C7 00 00 
[WR   /7555/A9] 04 C7 00 00 04 C7 00 00 

Common Flash Interface Data: No data provided

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board. For ROM writing, you can give the option called “Generic Flash Cartridge (WR/555/A9)” a try at your own risk.

FlashGBX v3.21 | GBxCart RW v1.4a – Firmware R39+L8

**Comment by lesserkuma** [comment]
Please try again with FlashGBX v3.22 which was released today!
