### ISSUE TITLE
Need gbxcart_rw_v1.1-1.2_pcb_r31.hex

### ISSUE THREAD

**Issue by BarcelonaBITW95** [lesserkuma/FlashGBX#70]
Hi Here is the error message after I install the Firmware Update please help me asap, I need this for my weekend vacation. Thanks

<img width="649" alt="image" src="https://user-images.githubusercontent.com/126231210/221112497-aed1a8d8-145f-4407-a7be-645db082c827.png">

**Comment by lesserkuma** [comment]
Hi, before opening an issue, please first update to the latest version of FlashGBX:
https://github.com/lesserkuma/FlashGBX/releases/latest
