### ISSUE TITLE
Add profile for Fujitsu branded 29F106

### ISSUE THREAD

**Issue by sillyhatday** [lesserkuma/FlashGBX#71]
I have come across some Fujitsu branded chips for nearly half the price of AMD versions. After some tinkering you can get them to flash properly using the generic settings suggested. Could there be support to have its own profile properly auto detected? This is using my own design of MBC5 cartridge on my Github page. They work perfectly with AM29F016.

![image2](https://user-images.githubusercontent.com/65309612/227721230-990f8bfd-3419-46a0-85c9-501495a44660.png)

This is what is brought up after using Detect Flash Cart function below.

![image](https://user-images.githubusercontent.com/65309612/227721179-80f4ead2-fa6a-466f-a312-5b34de300a24.png)

**Comment by lesserkuma** [comment]
OK, if you could show me a picture of the chip with visible markings, I will add it in the next release!

**Comment by sillyhatday** [comment]
![20230326_002746](https://user-images.githubusercontent.com/65309612/227748812-f91d7cd8-2827-4d62-8174-47b299c59f66.jpg)

I hope this is clear enough. If not I can wait until there is daylight to send another

**Comment by sillyhatday** [comment]
![Uploading 20230326_110852.jpg…]()

**Comment by sillyhatday** [comment]
![20230326_110852](https://user-images.githubusercontent.com/65309612/227768961-aba4ec9b-9ae4-4650-a1f5-8ed570051f40.jpg)
