### ISSUE TITLE
MOTHER3 Repro can't be written

### ISSUE THREAD

**Issue by redwolf2** [lesserkuma/FlashGBX#84]
`CFI ERROR: Couldn’t retrieve sector size map from the cartridge.`

The following cartridge configuration was detected:

ROM Title: MOTHER3

Flash ID Check:
[   ROM   ] 1C 00 FA 00 1C 00 FA 00 
[   555/AA] 1C 00 FA 00 00 00 00 00 
[  5555/AA] 1C 00 FA 00 00 00 00 00 
[   AAA/AA] 1C 00 FA 00 00 00 00 00 
[  AAAA/AA] 1C 00 FA 00 00 00 00 00 
[  4555/AA] 1C 00 FA 00 00 00 00 00 
[  7555/AA] 1C 00 FA 00 00 00 00 00 
[  4AAA/AA] 1C 00 FA 00 00 00 00 00 
[  7AAA/AA] 1C 00 FA 00 00 00 00 00 
[     0/90] 1C 00 FA 00 1C 00 FA 00 

Common Flash Interface Data:
Device size: 0x2000000 (32.00 MiB)
Voltage: 2.7–3.6 V
Single write: True
Buffered write: True (256 Bytes)
Chip erase: 524288–2097152 ms
Sector erase: 2048–8192 ms
Region 1: 0x0000000–0x001FFFF @ 0x4000 Bytes × 8
Region 2: 0x0020000–0x1FFFFFF @ 0x20000 Bytes × 255

Cartridge Type: Unknown flash cartridge – Please submit the displayed information along with a picture of the cartridge’s circuit board. For ROM writing, you can give the option called “Generic Flash Cartridge (0/90)” a try at your own risk.

FlashGBX v3.31 | GBxCart RW v1.4a/b – Firmware R42+L10

![cartridge](https://github.com/lesserkuma/FlashGBX/assets/4141621/2d1f7be1-4c49-4943-8c71-cd1633dbdcc9)
![cardridge_back](https://github.com/lesserkuma/FlashGBX/assets/4141621/2872d473-4334-4b85-99df-5bc8ce9e78c7)

**Comment by lesserkuma** [comment]
What happens if you manually select `36L0R8-39VF512 with M36L0R8060B` instead of going through the auto-detect?

**Comment by lesserkuma** [comment]
Support was added with FlashGBX v3.32, thanks to a contribution by user marv17.

**Comment by redwolf2** [comment]
I can confirm, that it worked for me.
