### ISSUE TITLE
Support request for DIY SST27SF256

### ISSUE THREAD

**Issue by MarcusWegener** [lesserkuma/FlashGBX#87]
Hi, 
I'm trying to rebuild this cartridge. 
Do you think this can be written with FlashGBX?

Thank you very much!

https://hackaday.io/project/4291-homebrew-gameboy-cartridge
https://github.com/Xyl2k/Gameboy-Color-Cartridge
https://de.scribd.com/document/639696691/SST27SF256-datasheet#

**Comment by lesserkuma** [comment]
Hi! That doesn't seem to be possible via GBxCart RW and FlashGBX as that flash chip uses 12V for erasing and programming.

**Comment by happysoul** [comment]
this chip only have 32KB, maybe less then 10 games match with out a MBC chip.
you can use other chip, can be rewrite with 5V, like 28, 29, 39,  28C256 29C010 29C020 29C040 ... sst39sf010 020 040...
![image](https://github.com/lesserkuma/FlashGBX/assets/3378160/352d00a4-9003-403d-b4df-1e3b787f8466)
![image](https://github.com/lesserkuma/FlashGBX/assets/3378160/efa12276-9419-4140-a321-a6fb323abdf8)
