### ISSUE TITLE
Cannot backup or write roms

### ISSUE THREAD

**Issue by teamsuperpanda** [lesserkuma/FlashGBX#9]
Any tips? This screenshot is as far as I get to backing up a real gameboy rom.
I also get the "Operation stopped" when I try and write a valid rom too

![Screen Shot 2021-04-15 at 7 18 36 PM](https://user-images.githubusercontent.com/60556240/114829695-82c42700-9e1f-11eb-87a3-c2de2a0291f6.png)

**Comment by lesserkuma** [comment]
Hey, thanks for the issue report! I remember there was a bug in version 1.4, did you try if the same still happens with the latest version 1.4.2? You can also try to update the firmware to R29 which should also resolve the problem.

**Comment by teamsuperpanda** [comment]
Thank you for your help. Installed 1.4.2 and everything is working!
