### ISSUE TITLE
Support for HC007-BGA-V2 -- save file not being erased nor overwritten

### ISSUE THREAD

**Issue by LordRembo** [lesserkuma/FlashGBX#90]
I've recently gotten some of these cartridges (see pictures). The exact cart type is not in the supported list, but it treats it as compatible with:
- SD007_48BALL_64M with M29W640*
- SD007_BGA48_71TV_T28_DEEP with M29W640
- SD007_T40_48BALL_71_TV_TS28 with M29W640

The problem I'm having though, is that I can flash ROMs on it but I can't erase, nor restore save data to the cart. What could be causing this?
I'm using FlashGBX v3.34 | GBxCart RW v1.3 – Firmware L1

These are the specs the reader returned:
```
ROM Size: 4 MiB
Save type: 1M SRAM (128KiB)
Mapper type: default (MBC5)

Common Flash Interface Data:
Swapped pins: (0, 1)
Device size: 0x0800000 (8.00 MiB)
Voltage: 2.7–3.6 V
Single write: True
Buffered write: True (32 Bytes)
Sector erase: 1024–8192 ms
Sector flags: 0x05
Region 1: 0x0000000–0x07FFFFF @ 0x10000 Bytes × 128

```
![367841280_855936322845147_2230804470966500586_n](https://github.com/lesserkuma/FlashGBX/assets/758957/071559ff-1a06-4f20-866a-bc6cec7c27c7)
![20231101_095219](https://github.com/lesserkuma/FlashGBX/assets/758957/c13df793-b69d-4e8a-bce9-d928982e084f)
![20231101_095228](https://github.com/lesserkuma/FlashGBX/assets/758957/3309b1ab-e0b0-42b2-bdc4-03da1a0a12d8)

**Comment by lesserkuma** [comment]
Hi, looks like this cartridge lacks the battery power for its SRAM chip, so save data will not be retained after it loses console/cartreader power. These kinds of cartridges are not designed to work with unmodified ROMs and are usually sold with a modification that copies the save data from SRAM into flash ROM space while the console is running. For Game Boy, FlashGBX cannot directly access save data that is embedded into the ROM. See [this page](https://flashcartdb.com/index.php/Clone_and_Repro_Cart_Problems) for more information.
