### ISSUE TITLE
[REQUEST] High DPI GUI

### ISSUE THREAD

**Issue by Clads92** [lesserkuma/FlashGBX#94]
Hi,

Thanks for this awesome work, but on my 4K screen the gui is very tiny, it's possible to get high dpi feature for a future version please ?
![Capture d'écran 2023-11-22 213516](https://github.com/lesserkuma/FlashGBX/assets/16538756/12c8a2bf-f79c-4c07-ab1a-7471314ce0fe)

**Comment by lesserkuma** [comment]
Hi! Is this a computer with just one display connected or do you have multiple displays? If it's more than one display, do they run on different DPI?

**Comment by Clads92** [comment]
It's a mono display (LG cx oled)
Thanks for your reply

**Comment by lesserkuma** [comment]
I think it's a bug with the GUI framework ([PySide2](https://pypi.org/project/PySide2/)).
If you're comfortable installing [Python](https://www.python.org/downloads/) on your system, you can then enter this in a Terminal window:
```cmd
pip install "FlashGBX[qt6]"
python -m FlashGBX
```
This would make it use the newer PySide6 framework instead. I hope this works better.

**Comment by Clads92** [comment]
Hi, worked like a charm, thanks

**Comment by lesserkuma** [comment]
Sounds good! I'll try to add a PySide6/Qt6 portable version for the next release.
